version: '3.4'

services:

  local:
    stdin_open: true
    tty: true
    image: dleongsh/s4:v1.10.0
    ports:
      - 6006:6006
      - 8888:8888
    environment:
      NVIDIA_VISIBLE_DEVICES: 0
    volumes:
      - /home/daniel/projects/state-spaces:/s4
      - /home/daniel/datasets:/datasets
    ulimits:
      memlock: -1
      stack: 67108864
    shm_size: 16gb
    # command: jupyter notebook --allow-root --ip 0.0.0.0
    # command: tensorboard --logdir /logs --host 0.0.0.0 --port 6006